(define-key isearch-mode-map "\M-ss" 'avy-isearch)
(global-set-key "\M-gw" 'avy-goto-word-0)
(global-set-key "\M-g\M-l" 'avy-goto-line)
(global-set-key "\M-g\M-c" 'avy-goto-char)
(global-set-key "\M-g\M-i" 'avy-goto-char-in-line)
