;;; lollypop-unicorn-theme.el --- an Emacs 24 theme based on Lollypop unicorn (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1417407757
;;; Original author: Ted de Koning
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Lollypop unicorn (tmTheme) by Ted de Koning
;;
;;; Code:

(deftheme lollypop-unicorn
  "lollypop-unicorn-theme - Created by tmtheme-to-deftheme - 2014-12-01 12:22:37 +0800")

(custom-theme-set-variables
 'lollypop-unicorn
)

(custom-theme-set-faces
 'lollypop-unicorn
 ;; basic theming.

 '(default ((t (:foreground "#d1d1d1" :background "#464646" ))))
 '(region  ((t (:background "#d15cd1"))))
 '(cursor  ((t (:background "#d1c9d1"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#626262"  :background "#545454" ))))
 '(fringe                              ((t (                       :background "#545454" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#a7a7a7"  :background "#545454" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#d1d1d1"  :background "#545454" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#d1d1d1"  :italic t))))
 '(font-lock-preprocessor-face ((t (:foreground "#d15cd1"  ))))
 '(font-lock-string-face ((t (:foreground "#d0aeaf"  ))))
 '(font-lock-builtin-face ((t (:foreground "#c6c6bc"  :bold t))))
 '(font-lock-keyword-face ((t (:foreground "#cb84d1"  ))))
 '(js3-function-param-face ((t (:foreground "#b682c9"  ))))
 '(js2-function-param ((t (:foreground "#b682c9"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#d1cecb"  :bold t))))
 '(font-lock-function-name-face ((t (:foreground "#d1d0b2"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#d1d1d1"  :italic t))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#934193"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#a148a2"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#b04eb0"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#b75db7"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#bd6bbe"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#c47ac4"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#ca89cb"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d197d1"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#d7a6d8"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lollypop-unicorn)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; lollypop-unicorn-theme.el ends here
