;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-visual-line
        cua-cut-region
        cua-paste
        cua-scroll-up
        end-of-visual-line
        keyboard-escape-quit
        multiple-cursors-mode
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cua-scroll-down
        end-of-buffer
        ))
