;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-visual-line
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-scroll-up
        dabbrev-expand
        embrace-add
        end-of-visual-line
        indent-for-tab-command
        keyboard-escape-quit
        multiple-cursors-mode
        nxml-electric-slash
        ruby-end-space
        slim-electric-backspace
        smart-beginning-of-line
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cua-scroll-down
        delete-horizontal-space
        end-of-buffer
        iedit-mode
        mac-mwheel-scroll
        repeat
        set-fill-column
        smex
        ))
