(deftheme suckers "DOCSTRING for suckers")
(custom-theme-set-faces 'suckers
                        '(default ((t (:foreground "#fdf4c1" :background "#282828" ))))
                        '(cursor ((t (:background "#fdf4c1" ))))
                        '(fringe ((t (:background "#282828" ))))
                        '(mode-line ((t (:foreground "#ece09f" :background "#1e1c1a" ))))
                        '(region ((t (:background "#504945" ))))
                        '(font-lock-builtin-face ((t (:foreground "#fe8019" ))))
                        '(font-lock-comment-face ((t (:foreground "#7c6f64" ))))
                        '(font-lock-function-name-face ((t (:foreground "#a99865" ))))
                        '(font-lock-keyword-face ((t (:foreground "#dd6f48" ))))
                        '(font-lock-string-face ((t (:foreground "#429489" ))))
                        '(font-lock-type-face ((t (:foreground "#66999d" ))))
                        '(font-lock-constant-face ((t (:foreground "#bbaa97" ))))
                        '(font-lock-variable-name-face ((t (:foreground "#83a598" ))))
                        '(minibuffer-prompt ((t (:foreground "#61acbb"))))
                        '(font-lock-warning-face ((t (:foreground "red"))))
                        )
(provide-theme 'suckers)
