;;; suede-shoes-theme.el --- an Emacs 24 theme based on Suede Shoes (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1417407745
;;; Original author: Jasonm23
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Suede Shoes (tmTheme) by Jasonm23
;;
;;; Code:

(deftheme suede-shoes
  "suede-shoes-theme - Created by tmtheme-to-deftheme - 2014-12-01 12:22:25 +0800")

(custom-theme-set-variables
 'suede-shoes
)

(custom-theme-set-faces
 'suede-shoes
 ;; basic theming.

 '(default ((t (:foreground "#e5e8d3" :background "#25333c" ))))
 '(region  ((t (:background "#DDF0FF"))))
 '(cursor  ((t (:background "#5e9ca7"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#4b575a"  :background "#38454b" ))))
 '(fringe                              ((t (                       :background "#38454b" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#c3ca99"  :background "#38454b" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#e5e8d3"  :background "#38454b" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#717171"  :italic t))))
 '(font-lock-constant-face ((t (:foreground "#dc836d"  ))))
 '(font-lock-type-face ((t (:foreground "#b4845c"  ))))
 '(font-lock-keyword-face ((t (:foreground "#e5e389"  ))))
 '(font-lock-string-face ((t (:foreground "#a8a8a8"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#afb6c0"  ))))
 '(font-lock-warning-face ((t (:foreground "#cfcfcf"  :italic t :underline t))))
 '(error ((t (:foreground "#cfcfcf" :background "#404346" ))))
 '(font-lock-preprocessor-face ((t (:foreground "#c7c7c7"  ))))
 '(diff-removed ((t (:foreground "#cfcfcf" :background "#5f3536" ))))
 '(diff-changed ((t (:foreground "#cfcfcf" :background "#3b5d65" ))))
 '(diff-added ((t (:foreground "#cfcfcf" :background "#4e6844" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#717171"  :italic t))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#7f5d41"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#8b6647"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#98704e"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#a57954"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#ad835f"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#b48c6c"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#ba9678"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#c1a085"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#c7aa92"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'suede-shoes)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; suede-shoes-theme.el ends here
