(defun yas-chai-matcher-list ()
  '(".to"
    ".be"
    ".been"
    ".is"
    ".that"
    ".which"
    ".and"
    ".has"
    ".have"
    ".with"
    ".at"
    ".of"
    ".same"
    ".not"
    ".deep"
    ".any"
    ".all"
    ".a(type)"
    ".include(value)"
    ".ok"
    ".true"
    ".false"
    ".null"
    ".undefined"
    ".NaN"
    ".exist"
    ".empty"
    ".arguments"
    ".equal(value)"
    ".eql(value)"
    ".above(value)"
    ".least(value)"
    ".below(value)"
    ".most(value)"
    ".within(start, finish)"
    ".instanceof(constructor)"
    ".property(name, [value])"
    ".ownProperty(name)"
    ".ownPropertyDescriptor(name[, descriptor[, message]])"
    ".length"
    ".lengthOf(value[, message])"
    ".match(regexp)"
    ".string(string)"
    ".keys(key1, [key2], […])"
    ".throw(constructor)"
    ".respondTo(method)"
    ".itself"
    ".satisfy(method)"
    ".closeTo(expected, delta)"
    ".members(set)"
    ".oneOf(list)"
    ".change(function)"
    ".increase(function)"
    ".decrease(function)"
    ".extensible"
    ".sealed"
    ".frozen"))
