;;; twilight-theme.el --- an Emacs 24 theme based on Twilight (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme
;;; Version: 1403877864
;;; Original author: Michael Sheets
;;; Url: https://github.com/emacsfodder/tmThemeToDeftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme,
;;  from Twilight (tmTheme) by Michael Sheets
;;
;;; Code:

(deftheme twilight
  "twilight-theme - Created by tmtheme-to-deftheme - 2014-06-27 22:04:24 +0800")

(custom-theme-set-variables
 'twilight
 '(linum-format " %7i ")
 '(fringe-mode 5 nil (fringe))
)

(custom-theme-set-faces
 'twilight
 ;; basic theming.

 '(default ((t (:foreground "#F8F8F8" :background "#181818"))))
 '(region  ((t (:background "#DDF0FF33"))))
 '(cursor  ((t (:background "#A7A7A7"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#2e2e2e"  :background "#1f1f1f" ))))
 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))
 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                       :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(fringe                              ((t (                       :background "#1f1f1f" ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))
 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))
 '(mode-line-inactive                  ((t (:foreground "#c6c6c6"  :background "#131313" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#f8f8f8"  :background "#0e0e0e" :box nil ))))
 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))
 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))
 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))

 '(font-lock-comment-face ((t (:foreground "#5f5a60" ))))
 '(font-lock-constant-face ((t (:foreground "#cf6a4c" ))))
 '(font-lock-type-face ((t (:foreground "#9b703f" ))))
 '(font-lock-keyword-face ((t (:foreground "#cda869" ))))
 '(font-lock-string-face ((t (:foreground "#8f9d6a" ))))
 '(font-lock-variable-name-face ((t (:foreground "#7587a6" ))))
 '(font-lock-warning-face ((t (:foreground "#d2a8a1" ))))
 '(error ((t (:foreground "#f8f8f8" :background "#462846"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8996a8" ))))
 '(diff-removed ((t (:foreground "#f8f8f8" :background "#420e09"))))
 '(diff-changed ((t (:foreground "#f8f8f8" :background "#4a410d"))))
 '(diff-added ((t (:foreground "#f8f8f8" :background "#253b22"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5f5a60" ))))
)

;; Rainbow delimiters
(defun twilight-rainbow-delim-set-face ()
  (set-face-attribute 'rainbow-delimiters-depth-1-face nil :foreground "#6d4f2d")
  (set-face-attribute 'rainbow-delimiters-depth-2-face nil :foreground "#785731")
  (set-face-attribute 'rainbow-delimiters-depth-3-face nil :foreground "#835f35")
  (set-face-attribute 'rainbow-delimiters-depth-4-face nil :foreground "#8e673a")
  (set-face-attribute 'rainbow-delimiters-depth-5-face nil :foreground "#996f3e")
  (set-face-attribute 'rainbow-delimiters-depth-6-face nil :foreground "#a47743")
  (set-face-attribute 'rainbow-delimiters-depth-7-face nil :foreground "#af7e47")
  (set-face-attribute 'rainbow-delimiters-depth-8-face nil :foreground "#b7864e")
  (set-face-attribute 'rainbow-delimiters-depth-9-face nil :foreground "#bb8e59")
  (set-face-attribute 'rainbow-delimiters-unmatched-face nil :foreground "#FF0000"))

(eval-after-load "rainbow-delimiters" '(twilight-rainbow-delim-set-face))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'twilight)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; twilight-theme.el ends here
