
#+TITLE: Manipulate the Contents of Emacs Buffers
#+AUTHOR: Phillip Lord

#+INFOJS_OPT: view:info toc:nil


* Introduction

m-buffer provides functions for accessing and manipulating the contents of an
Emacs buffer. While Emacs already provides these features, m-buffer provides a
higher-level interaction. It achieves this in several ways: many of the
functions are list-orientated, so avoiding the need for iteration; it avoids
the use of global emacs state whenever it can be avoided, so avoiding
side-effects. And, it adds some macros for cleanup, so again, helping to
manage the process of global state where it can be avoided.


** Status

`m-buffer' is a work in progress, but much of it is now stable and the
interface should change only in forward-compatible ways for 1.0 release.
The individual files have statements about their stability.

** Caveat to Documentation

This is the first version of m-buffer with full [[http://github.com/phillord/lentic][lenticular]] documentation. Both
lentic and this documentation are a work in progress. They will improve.


* m-buffer

m-buffer.el provides list-orientated search both for any regexp and standard
regexps, as well as the ability to do things with these matches: replace, add
overlays or text-properties or, most generically of all, call any function on
matches.

#+include: "m-buffer.org" :minlevel 2


* m-buffer-at

m-buffer-at.el provides a set of stateless functions which for accessing data
about buffers, without requiring changing the `current-buffer'.

#+include: "m-buffer-at.org" :minlevel 2


* m-buffer-macro

m-buffer-macro.el provides some general purpose macros for:
 
 - dealing with markers and their cleanup
 - running code at a specific location

#+include: "m-buffer-macro.org" :minlevel 2


* m-buffer-benchmark

m-buffer-benchmark.el provides no functions, but is a set of benchmarks to
give some idea of how much overhead various m-buffer functions entail.

#+include: "m-buffer-benchmark.org" :minlevel 2

* Roadmap

** 0.11

Full lentic documentation using lentic-server


** 0.12

Completion of m-buffer-at with all the core buffer functions.
