(defun color-theme-splodge ()
  (interactive)
  (color-theme-install
   '(color-theme-splodge
      ((background-color . "#0f061e")
      (background-mode . dark)
      (border-color . "#471010")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#471010"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#323232"))))
     (font-lock-builtin-face ((t (:foreground "#0099b0"))))
     (font-lock-comment-face ((t (:foreground "#70ffa0"))))
     (font-lock-function-name-face ((t (:foreground "#00adfc"))))
     (font-lock-keyword-face ((t (:foreground "#05dfd2"))))
     (font-lock-string-face ((t (:foreground "#00b2ff"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#00dcff"))))
     (font-lock-variable-name-face ((t (:foreground "#83ffd8"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-splodge)