(defun color-theme-twilight ()
  (interactive)
  (color-theme-install
   '(color-theme-twilight
      ((background-color . "#141414")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#a7a7a7")
      (foreground-color . "#f8f8f8")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#27292a"))))
     (font-lock-builtin-face ((t (:foreground "#cacaca"))))
     (font-lock-comment-face ((t (:foreground "#5f5a60"))))
     (font-lock-function-name-face ((t (:foreground "#9b703f"))))
     (font-lock-keyword-face ((t (:foreground "#cda869"))))
     (font-lock-string-face ((t (:foreground "#8f9d6a"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#cf6a4c"))))
     (font-lock-variable-name-face ((t (:foreground "#7587a6"))))
     (minibuffer-prompt ((t (:foreground "#5f5a60" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-twilight)
