(defun color-theme-carnivale-854847 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/854847/"
  (interactive)
  (color-theme-install
   '(color-theme-carnivale-854847
     ((background-color . "#000500")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#7EFFC6"))))
     (font-lock-constant-face ((t (:foreground "#E255FF"))))
     (font-lock-builtin-face ((t (:foreground "#FF8876"))))
     (font-lock-function-name-face ((t (:foreground "#2F8F78"))))
     (font-lock-variable-name-face ((t (:foreground "#FF8DA6"))))
     (font-lock-keyword-face ((t (:foreground "#FFF03E"))))
     (font-lock-string-face ((t (:foreground "#FFDA58"))))
     (font-lock-doc-string-face ((t (:foreground "#FFDA58"))))
     (font-lock-type-face ((t (:foreground "#FFC9C6"))))
     )))

(provide 'color-theme-carnivale-854847)