(defun color-theme-deepblueday ()
  (interactive)
  (color-theme-install
   '(color-theme-deepblueday
      ((background-color . "#000407")
      (background-mode . light)
      (border-color . "#05202e")
      (cursor-color . "#0d4d6d")
      (foreground-color . "#ddf3ff")
      (mouse-color . "black"))
     (fringe ((t (:background "#05202e"))))
     (mode-line ((t (:foreground "#47c0ff" :background "#0b222d"))))
     (region ((t (:background "#004361"))))
     (font-lock-builtin-face ((t (:foreground "#0b5e8e"))))
     (font-lock-comment-face ((t (:foreground "#264e5f"))))
     (font-lock-function-name-face ((t (:foreground "#60a8c3"))))
     (font-lock-keyword-face ((t (:foreground "#0a79bd"))))
     (font-lock-string-face ((t (:foreground "#aad9ee"))))
     (font-lock-type-face ((t (:foreground"#1f678e"))))
     (font-lock-constant-face ((t (:foreground "#1aa6e9"))))
     (font-lock-variable-name-face ((t (:foreground "#0e84be"))))
     (minibuffer-prompt ((t (:foreground "#00d8fa" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-deepblueday)
