(defun color-theme-jadedragon-660650 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/660650/"
  (interactive)
  (color-theme-install
   '(color-theme-jadedragon-660650
     ((background-color . "#0D0000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#6DA1C3"))))
     (font-lock-constant-face ((t (:foreground "#6CE7C2"))))
     (font-lock-builtin-face ((t (:foreground "#00E1AD"))))
     (font-lock-function-name-face ((t (:foreground "#36FFBA"))))
     (font-lock-variable-name-face ((t (:foreground "#63FF2B"))))
     (font-lock-keyword-face ((t (:foreground "#00A3A2"))))
     (font-lock-string-face ((t (:foreground "#00FFC0"))))
     (font-lock-doc-string-face ((t (:foreground "#00FFC0"))))
     (font-lock-type-face ((t (:foreground "#00AAB1"))))
     )))

(provide 'color-theme-jadedragon-660650)