;;; resesif-boned-theme.el --- an Emacs 24 theme based on Resesif Boned (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1404021812
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Resesif Boned (tmTheme) by 
;;
;;; Code:

(deftheme resesif-boned
  "resesif-boned-theme - Created by tmtheme-to-deftheme - 2014-06-29 14:03:32 +0800")

(custom-theme-set-variables
 'resesif-boned
)

(custom-theme-set-faces
 'resesif-boned
 ;; basic theming.

 '(default ((t (:foreground "#E6E1DC" :background "#17171716" ))))
 '(region  ((t (:background "#5A647EE0"))))
 '(cursor  ((t (:background "#FFFFFF"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#403f3e"  :background "#2c2b2b" ))))
 '(fringe                              ((t (                       :background "#2c2b2b" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#c0b4a8"  :background "#2c2b2b" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#e6e1dc"  :background "#2c2b2b" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#414141"  ))))
 '(font-lock-keyword-face ((t (:foreground "#B6C34D"  ))))
 '(font-lock-constant-face ((t (:foreground "#C29B7A" :background "#26211d" ))))
 '(font-lock-builtin-face ((t (:foreground "#71BACC"  ))))
 '(font-lock-string-face ((t (:foreground "#B0CC66" :background "#1e201a" ))))
 '(diff-added ((t (:foreground "#E6E1DC" :background "#043202" ))))
 '(diff-removed ((t (:foreground "#E6E1DC" :background "#550000" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#414141"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#886d56"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#96785e"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#a1836a"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#aa8f77"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#b29a85"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#bba592"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#c3b0a0"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#ccbcae"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#d5c7bb"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'resesif-boned)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; resesif-boned-theme.el ends here
