(autoload 'hyde/hyde-file-local-uncommitted-changed "hyde" "local uncommitted changed" t nil)
(autoload 'hyde/hyde-file-committed-not-pushed "hyde" "file committed not pushed" t nil)
(autoload 'hyde/hyde-file-committed-pushed "hyde" "file committed pushed" t nil)
(autoload 'hyde/hyde-add-file "hyde" "add file" t nil)
(autoload 'hyde/hyde-rename-file "hyde" "rename file" t nil)
(autoload 'hyde/hyde-commit-post "hyde" "vc commit post" t nil)
(autoload 'hyde/hyde-push "hyde" "vc push" t nil)
(autoload 'hyde/run-jekyll "hyde" "run jekyll command" t nil)
(autoload 'hyde/deploy "hyde" "deploy" t nil)
(autoload 'hyde/promote-to-post "hyde" "promote draft to post" t nil)
(autoload 'hyde/open-post-maybe "hyde" "open post, maybe" t nil)
(autoload 'hyde/new-post "hyde" "new post" t nil)
(autoload 'hyde/quit "hyde" "quit" t nil)
(autoload 'hyde/load-posts "hyde" "Load posts" t nil)
(autoload 'hyde "hyde" "Enters hyde mode" t nil)
(autoload 'hyde/read-config "hyde" "Read config" nil nil)
(autoload 'hyde/hyde-mode "hyde" "Hyde mode" nil nil)
(provide 'hyde-autoloads)

