(defun color-theme-coolingtower-812522 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/812522/"
  (interactive)
  (color-theme-install
   '(color-theme-coolingtower-812522
     ((background-color . "#030300")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#B4E99F"))))
     (font-lock-constant-face ((t (:foreground "#02C064"))))
     (font-lock-builtin-face ((t (:foreground "#5ACDB5"))))
     (font-lock-function-name-face ((t (:foreground "#FFFF9B"))))
     (font-lock-variable-name-face ((t (:foreground "#A3BC54"))))
     (font-lock-keyword-face ((t (:foreground "#BFFDFE"))))
     (font-lock-string-face ((t (:foreground "#97F9F1"))))
     (font-lock-doc-string-face ((t (:foreground "#97F9F1"))))
     (font-lock-type-face ((t (:foreground "#B4FBFF"))))
     )))

(provide 'color-theme-coolingtower-812522)