(defun color-theme-autummmn-677293 ()
  ;; color-theme-Autummmn
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/677293/"
  (interactive)
  (color-theme-install
   '(color-theme-autummmn-677293
     ((background-color . "#18000B")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FFAB3B"))))
     (font-lock-constant-face ((t (:foreground "#78FD24"))))
     (font-lock-builtin-face ((t (:foreground "#D9C919"))))
     (font-lock-function-name-face ((t (:foreground "#8E7145"))))
     (font-lock-variable-name-face ((t (:foreground "#FFECA3"))))
     (font-lock-keyword-face ((t (:foreground "#A58019"))))
     (font-lock-string-face ((t (:foreground "#FF8604"))))
     (font-lock-doc-string-face ((t (:foreground "#FF8604"))))
     (font-lock-type-face ((t (:foreground "#9FEB17"))))
     )))

(provide 'color-theme-autummmn-677293)