(defun color-theme-wholegrain-807102 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/807102/"
  (interactive)
  (color-theme-install
   '(color-theme-wholegrain-807102
     ((background-color . "#090108")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#E2FE9D"))))
     (font-lock-constant-face ((t (:foreground "#E59DE2"))))
     (font-lock-builtin-face ((t (:foreground "#C4A800"))))
     (font-lock-function-name-face ((t (:foreground "#FFFF75"))))
     (font-lock-variable-name-face ((t (:foreground "#C4B3B2"))))
     (font-lock-keyword-face ((t (:foreground "#7F9E54"))))
     (font-lock-string-face ((t (:foreground "#E7D300"))))
     (font-lock-doc-string-face ((t (:foreground "#E7D300"))))
     (font-lock-type-face ((t (:foreground "#FFD836"))))
     )))

(provide 'color-theme-wholegrain-807102)