(defun color-theme-militia-936329 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/936329/"
  (interactive)
  (color-theme-install
   '(color-theme-militia-936329
     ((background-color . "#000E03")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#57FF8D"))))
     (font-lock-constant-face ((t (:foreground "#C9AD65"))))
     (font-lock-builtin-face ((t (:foreground "#519924"))))
     (font-lock-function-name-face ((t (:foreground "#BDF29A"))))
     (font-lock-variable-name-face ((t (:foreground "#19FF00"))))
     (font-lock-keyword-face ((t (:foreground "#9E965A"))))
     (font-lock-string-face ((t (:foreground "#E87300"))))
     (font-lock-doc-string-face ((t (:foreground "#E87300"))))
     (font-lock-type-face ((t (:foreground "#55CE0C"))))
     )))

(provide 'color-theme-militia-936329)