
(defun color-theme-grassyknoll-788556 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/788556/"
  (interactive)
  (color-theme-install
   '(color-theme-grassyknoll-788556
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#CCA063"))))
     (font-lock-constant-face ((t (:foreground "#CCC158"))))
     (font-lock-builtin-face ((t (:foreground "#ACFB2C"))))
     (font-lock-function-name-face ((t (:foreground "#D23F1A"))))
     (font-lock-variable-name-face ((t (:foreground "#599B00"))))
     (font-lock-keyword-face ((t (:foreground "#696676"))))
     (font-lock-string-face ((t (:foreground "#00FF00"))))
     (font-lock-doc-string-face ((t (:foreground "#00FF00"))))
     (font-lock-type-face ((t (:foreground "#86F410"))))
     )))

(provide 'color-theme-grassyknoll-788556)