(defun color-theme-aquamarina-762835 ()
  "Theme generated by Sweyla: http://inspiration-theme.sweyla.com/code/seed/762835/"
  (interactive)
  (color-theme-install
   '(color-theme-aquamarina-762835
     ((background-color . "#07050D")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#00A3FF"))))
     (font-lock-constant-face ((t (:foreground "#2978FF"))))
     (font-lock-builtin-face ((t (:foreground "#02F8FF"))))
     (font-lock-function-name-face ((t (:foreground "#60F5FF"))))
     (font-lock-variable-name-face ((t (:foreground "#00B7C2"))))
     (font-lock-keyword-face ((t (:foreground "#55BDB5"))))
     (font-lock-string-face ((t (:foreground "#FFFF7C"))))
     (font-lock-doc-string-face ((t (:foreground "#FFFF7C"))))
     (font-lock-type-face ((t (:foreground "#D5E8B1"))))
     )))

(provide 'color-theme-aquamarina-762835)
