(defun color-theme-verdantparty-794284 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/794284/"
  (interactive)
  (color-theme-install
   '(color-theme-verdantparty-794284
     ((background-color . "#0A0701")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#71FFD3"))))
     (font-lock-constant-face ((t (:foreground "#A9FA90"))))
     (font-lock-builtin-face ((t (:foreground "#A0FF75"))))
     (font-lock-function-name-face ((t (:foreground "#1AD01A"))))
     (font-lock-variable-name-face ((t (:foreground "#37FFA2"))))
     (font-lock-keyword-face ((t (:foreground "#52FFBF"))))
     (font-lock-string-face ((t (:foreground "#88FF65"))))
     (font-lock-doc-string-face ((t (:foreground "#88FF65"))))
     (font-lock-type-face ((t (:foreground "#91FFEB"))))
     )))

(provide 'color-theme-verdantparty-794284)