(defun color-theme-jadedragon ()
  (interactive)
  (color-theme-install
   '(color-theme-jadedragon
      ((background-color . "#000000")
      (background-mode . dark)
      (border-color . "#000c0f")
      (cursor-color . "#00a3a2")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#000c0f"))))
     (mode-line ((t (:foreground "#828282" :background "#0f1e24"))))
     (region ((t (:background "#081e20"))))
     (font-lock-builtin-face ((t (:foreground "#ffffff"))))
     (font-lock-comment-face ((t (:foreground "#6da1c3"))))
     (font-lock-function-name-face ((t (:foreground "#36ffba"))))
     (font-lock-keyword-face ((t (:foreground "#00a3a2"))))
     (font-lock-string-face ((t (:foreground "#00ffc0"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#6ce7c2"))))
     (font-lock-variable-name-face ((t (:foreground "#63ff2b"))))
     (minibuffer-prompt ((t (:foreground "#14948b" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-jadedragon)