(defun color-theme-mossysparks-825884 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/825884/"
  (interactive)
  (color-theme-install
   '(color-theme-mossysparks-825884
     ((background-color . "#021100")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#5BEDA7"))))
     (font-lock-constant-face ((t (:foreground "#60EAB9"))))
     (font-lock-builtin-face ((t (:foreground "#21FF66"))))
     (font-lock-function-name-face ((t (:foreground "#54FFF0"))))
     (font-lock-variable-name-face ((t (:foreground "#CCC904"))))
     (font-lock-keyword-face ((t (:foreground "#8BFF97"))))
     (font-lock-string-face ((t (:foreground "#72B084"))))
     (font-lock-doc-string-face ((t (:foreground "#72B084"))))
     (font-lock-type-face ((t (:foreground "#3FFF46"))))
     )))

(provide 'color-theme-mossysparks-825884)